/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<
      '/action-popup/',
      '/action-popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/playground': RouteRecordInfo<
      '/action-popup/playground',
      '/action-popup/playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/404': RouteRecordInfo<
      '/common/404',
      '/common/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/about': RouteRecordInfo<
      '/common/about',
      '/common/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/change-log': RouteRecordInfo<
      '/common/change-log',
      '/common/change-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/features': RouteRecordInfo<
      '/common/features',
      '/common/features',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/help': RouteRecordInfo<
      '/common/help',
      '/common/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/privacy-policy': RouteRecordInfo<
      '/common/privacy-policy',
      '/common/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/terms-of-service': RouteRecordInfo<
      '/common/terms-of-service',
      '/common/terms-of-service',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content-script-iframe/': RouteRecordInfo<
      '/content-script-iframe/',
      '/content-script-iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools-panel/': RouteRecordInfo<
      '/devtools-panel/',
      '/devtools-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/': RouteRecordInfo<
      '/options-page/',
      '/options-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/install': RouteRecordInfo<
      '/setup/install',
      '/setup/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz': RouteRecordInfo<
      '/setup/SocialGlowz',
      '/setup/SocialGlowz',
      Record<never, never>,
      Record<never, never>,
      | '/setup/SocialGlowz/App'
      | '/setup/SocialGlowz/components/AppHeader'
      | '/setup/SocialGlowz/components/AppRightSidebar'
      | '/setup/SocialGlowz/components/AppSettings'
      | '/setup/SocialGlowz/components/AppSidebar'
      | '/setup/SocialGlowz/components/BackupRestore'
      | '/setup/SocialGlowz/components/BillingAccessPanel'
      | '/setup/SocialGlowz/components/CrmToolbar'
      | '/setup/SocialGlowz/components/DashboardFilters'
      | '/setup/SocialGlowz/components/ExtensionParitySurface'
      | '/setup/SocialGlowz/components/FriendsPanel'
      | '/setup/SocialGlowz/components/MobileLayout'
      | '/setup/SocialGlowz/components/MobileProfileSheet'
      | '/setup/SocialGlowz/components/MobileSettingsSheet'
      | '/setup/SocialGlowz/components/NetworkBrandIcon'
      | '/setup/SocialGlowz/components/NetworkWebviewHost'
      | '/setup/SocialGlowz/components/OnboardingFlow'
      | '/setup/SocialGlowz/components/PostAuthSyncOverlay'
      | '/setup/SocialGlowz/components/ProfileSwitcher'
      | '/setup/SocialGlowz/components/SignupNudge'
      | '/setup/SocialGlowz/components/SocialLogin'
      | '/setup/SocialGlowz/components/Unauthorized'
      | '/setup/SocialGlowz/components/common/NetworkLogo'
      | '/setup/SocialGlowz/components/common/SocialNetworkLogo'
      | '/setup/SocialGlowz/components/feed/CreatePost'
      | '/setup/SocialGlowz/components/feed/SocialAvatar'
      | '/setup/SocialGlowz/components/feed/SocialComment'
      | '/setup/SocialGlowz/components/feed/SocialPost'
      | '/setup/SocialGlowz/components/icons/NextdoorIcon'
      | '/setup/SocialGlowz/components/icons/QuoraIcon'
      | '/setup/SocialGlowz/components/icons/SnapchatIcon'
      | '/setup/SocialGlowz/components/icons/ThreadsIcon'
      | '/setup/SocialGlowz/components/kanban/KanbanBoard'
      | '/setup/SocialGlowz/components/kanban/KanbanSidebar'
      | '/setup/SocialGlowz/components/networks/DiscordView'
      | '/setup/SocialGlowz/components/networks/FacebookView'
      | '/setup/SocialGlowz/components/networks/GmailView'
      | '/setup/SocialGlowz/components/networks/InstagramView'
      | '/setup/SocialGlowz/components/networks/LinkedInView'
      | '/setup/SocialGlowz/components/networks/RedditView'
      | '/setup/SocialGlowz/components/networks/SnapchatView'
      | '/setup/SocialGlowz/components/networks/ThreadsView'
      | '/setup/SocialGlowz/components/networks/TikTokView'
      | '/setup/SocialGlowz/components/networks/TwitterView'
      | '/setup/SocialGlowz/views/LoginView'
      | '/setup/SocialGlowz/views/SessionLockView'
    >,
    '/setup/SocialGlowz/App': RouteRecordInfo<
      '/setup/SocialGlowz/App',
      '/setup/SocialGlowz/App',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/AppHeader': RouteRecordInfo<
      '/setup/SocialGlowz/components/AppHeader',
      '/setup/SocialGlowz/components/AppHeader',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/AppRightSidebar': RouteRecordInfo<
      '/setup/SocialGlowz/components/AppRightSidebar',
      '/setup/SocialGlowz/components/AppRightSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/AppSettings': RouteRecordInfo<
      '/setup/SocialGlowz/components/AppSettings',
      '/setup/SocialGlowz/components/AppSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/AppSidebar': RouteRecordInfo<
      '/setup/SocialGlowz/components/AppSidebar',
      '/setup/SocialGlowz/components/AppSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/BackupRestore': RouteRecordInfo<
      '/setup/SocialGlowz/components/BackupRestore',
      '/setup/SocialGlowz/components/BackupRestore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/BillingAccessPanel': RouteRecordInfo<
      '/setup/SocialGlowz/components/BillingAccessPanel',
      '/setup/SocialGlowz/components/BillingAccessPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/common/NetworkLogo': RouteRecordInfo<
      '/setup/SocialGlowz/components/common/NetworkLogo',
      '/setup/SocialGlowz/components/common/NetworkLogo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/common/SocialNetworkLogo': RouteRecordInfo<
      '/setup/SocialGlowz/components/common/SocialNetworkLogo',
      '/setup/SocialGlowz/components/common/SocialNetworkLogo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/CrmToolbar': RouteRecordInfo<
      '/setup/SocialGlowz/components/CrmToolbar',
      '/setup/SocialGlowz/components/CrmToolbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/DashboardFilters': RouteRecordInfo<
      '/setup/SocialGlowz/components/DashboardFilters',
      '/setup/SocialGlowz/components/DashboardFilters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/ExtensionParitySurface': RouteRecordInfo<
      '/setup/SocialGlowz/components/ExtensionParitySurface',
      '/setup/SocialGlowz/components/ExtensionParitySurface',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/feed/CreatePost': RouteRecordInfo<
      '/setup/SocialGlowz/components/feed/CreatePost',
      '/setup/SocialGlowz/components/feed/CreatePost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/feed/SocialAvatar': RouteRecordInfo<
      '/setup/SocialGlowz/components/feed/SocialAvatar',
      '/setup/SocialGlowz/components/feed/SocialAvatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/feed/SocialComment': RouteRecordInfo<
      '/setup/SocialGlowz/components/feed/SocialComment',
      '/setup/SocialGlowz/components/feed/SocialComment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/feed/SocialPost': RouteRecordInfo<
      '/setup/SocialGlowz/components/feed/SocialPost',
      '/setup/SocialGlowz/components/feed/SocialPost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/FriendsPanel': RouteRecordInfo<
      '/setup/SocialGlowz/components/FriendsPanel',
      '/setup/SocialGlowz/components/FriendsPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/icons/NextdoorIcon': RouteRecordInfo<
      '/setup/SocialGlowz/components/icons/NextdoorIcon',
      '/setup/SocialGlowz/components/icons/NextdoorIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/icons/QuoraIcon': RouteRecordInfo<
      '/setup/SocialGlowz/components/icons/QuoraIcon',
      '/setup/SocialGlowz/components/icons/QuoraIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/icons/SnapchatIcon': RouteRecordInfo<
      '/setup/SocialGlowz/components/icons/SnapchatIcon',
      '/setup/SocialGlowz/components/icons/SnapchatIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/icons/ThreadsIcon': RouteRecordInfo<
      '/setup/SocialGlowz/components/icons/ThreadsIcon',
      '/setup/SocialGlowz/components/icons/ThreadsIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/kanban/KanbanBoard': RouteRecordInfo<
      '/setup/SocialGlowz/components/kanban/KanbanBoard',
      '/setup/SocialGlowz/components/kanban/KanbanBoard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/kanban/KanbanSidebar': RouteRecordInfo<
      '/setup/SocialGlowz/components/kanban/KanbanSidebar',
      '/setup/SocialGlowz/components/kanban/KanbanSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/MobileLayout': RouteRecordInfo<
      '/setup/SocialGlowz/components/MobileLayout',
      '/setup/SocialGlowz/components/MobileLayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/MobileProfileSheet': RouteRecordInfo<
      '/setup/SocialGlowz/components/MobileProfileSheet',
      '/setup/SocialGlowz/components/MobileProfileSheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/MobileSettingsSheet': RouteRecordInfo<
      '/setup/SocialGlowz/components/MobileSettingsSheet',
      '/setup/SocialGlowz/components/MobileSettingsSheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/NetworkBrandIcon': RouteRecordInfo<
      '/setup/SocialGlowz/components/NetworkBrandIcon',
      '/setup/SocialGlowz/components/NetworkBrandIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/DiscordView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/DiscordView',
      '/setup/SocialGlowz/components/networks/DiscordView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/FacebookView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/FacebookView',
      '/setup/SocialGlowz/components/networks/FacebookView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/GmailView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/GmailView',
      '/setup/SocialGlowz/components/networks/GmailView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/InstagramView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/InstagramView',
      '/setup/SocialGlowz/components/networks/InstagramView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/LinkedInView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/LinkedInView',
      '/setup/SocialGlowz/components/networks/LinkedInView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/RedditView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/RedditView',
      '/setup/SocialGlowz/components/networks/RedditView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/SnapchatView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/SnapchatView',
      '/setup/SocialGlowz/components/networks/SnapchatView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/ThreadsView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/ThreadsView',
      '/setup/SocialGlowz/components/networks/ThreadsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/TikTokView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/TikTokView',
      '/setup/SocialGlowz/components/networks/TikTokView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/networks/TwitterView': RouteRecordInfo<
      '/setup/SocialGlowz/components/networks/TwitterView',
      '/setup/SocialGlowz/components/networks/TwitterView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/NetworkWebviewHost': RouteRecordInfo<
      '/setup/SocialGlowz/components/NetworkWebviewHost',
      '/setup/SocialGlowz/components/NetworkWebviewHost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/OnboardingFlow': RouteRecordInfo<
      '/setup/SocialGlowz/components/OnboardingFlow',
      '/setup/SocialGlowz/components/OnboardingFlow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/PostAuthSyncOverlay': RouteRecordInfo<
      '/setup/SocialGlowz/components/PostAuthSyncOverlay',
      '/setup/SocialGlowz/components/PostAuthSyncOverlay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/ProfileSwitcher': RouteRecordInfo<
      '/setup/SocialGlowz/components/ProfileSwitcher',
      '/setup/SocialGlowz/components/ProfileSwitcher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/SignupNudge': RouteRecordInfo<
      '/setup/SocialGlowz/components/SignupNudge',
      '/setup/SocialGlowz/components/SignupNudge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/SocialLogin': RouteRecordInfo<
      '/setup/SocialGlowz/components/SocialLogin',
      '/setup/SocialGlowz/components/SocialLogin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/components/Unauthorized': RouteRecordInfo<
      '/setup/SocialGlowz/components/Unauthorized',
      '/setup/SocialGlowz/components/Unauthorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/views/LoginView': RouteRecordInfo<
      '/setup/SocialGlowz/views/LoginView',
      '/setup/SocialGlowz/views/LoginView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/SocialGlowz/views/SessionLockView': RouteRecordInfo<
      '/setup/SocialGlowz/views/SessionLockView',
      '/setup/SocialGlowz/views/SessionLockView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/update': RouteRecordInfo<
      '/setup/update',
      '/setup/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/side-panel/': RouteRecordInfo<
      '/side-panel/',
      '/side-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/ui/action-popup/pages/index.vue': {
      routes:
        | '/action-popup/'
      views:
        | never
    }
    'src/ui/action-popup/pages/playground.vue': {
      routes:
        | '/action-popup/playground'
      views:
        | never
    }
    'src/ui/common/pages/404.vue': {
      routes:
        | '/common/404'
      views:
        | never
    }
    'src/ui/common/pages/about.vue': {
      routes:
        | '/common/about'
      views:
        | never
    }
    'src/ui/common/pages/change-log.vue': {
      routes:
        | '/common/change-log'
      views:
        | never
    }
    'src/ui/common/pages/features.vue': {
      routes:
        | '/common/features'
      views:
        | never
    }
    'src/ui/common/pages/help.vue': {
      routes:
        | '/common/help'
      views:
        | never
    }
    'src/ui/common/pages/privacy-policy.vue': {
      routes:
        | '/common/privacy-policy'
      views:
        | never
    }
    'src/ui/common/pages/terms-of-service.vue': {
      routes:
        | '/common/terms-of-service'
      views:
        | never
    }
    'src/ui/content-script-iframe/pages/index.vue': {
      routes:
        | '/content-script-iframe/'
      views:
        | never
    }
    'src/ui/devtools-panel/pages/index.vue': {
      routes:
        | '/devtools-panel/'
      views:
        | never
    }
    'src/ui/options-page/pages/index.vue': {
      routes:
        | '/options-page/'
      views:
        | never
    }
    'src/ui/setup/pages/install.vue': {
      routes:
        | '/setup/install'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz.vue': {
      routes:
        | '/setup/SocialGlowz'
        | '/setup/SocialGlowz/App'
        | '/setup/SocialGlowz/components/AppHeader'
        | '/setup/SocialGlowz/components/AppRightSidebar'
        | '/setup/SocialGlowz/components/AppSettings'
        | '/setup/SocialGlowz/components/AppSidebar'
        | '/setup/SocialGlowz/components/BackupRestore'
        | '/setup/SocialGlowz/components/BillingAccessPanel'
        | '/setup/SocialGlowz/components/CrmToolbar'
        | '/setup/SocialGlowz/components/DashboardFilters'
        | '/setup/SocialGlowz/components/ExtensionParitySurface'
        | '/setup/SocialGlowz/components/FriendsPanel'
        | '/setup/SocialGlowz/components/MobileLayout'
        | '/setup/SocialGlowz/components/MobileProfileSheet'
        | '/setup/SocialGlowz/components/MobileSettingsSheet'
        | '/setup/SocialGlowz/components/NetworkBrandIcon'
        | '/setup/SocialGlowz/components/NetworkWebviewHost'
        | '/setup/SocialGlowz/components/OnboardingFlow'
        | '/setup/SocialGlowz/components/PostAuthSyncOverlay'
        | '/setup/SocialGlowz/components/ProfileSwitcher'
        | '/setup/SocialGlowz/components/SignupNudge'
        | '/setup/SocialGlowz/components/SocialLogin'
        | '/setup/SocialGlowz/components/Unauthorized'
        | '/setup/SocialGlowz/components/common/NetworkLogo'
        | '/setup/SocialGlowz/components/common/SocialNetworkLogo'
        | '/setup/SocialGlowz/components/feed/CreatePost'
        | '/setup/SocialGlowz/components/feed/SocialAvatar'
        | '/setup/SocialGlowz/components/feed/SocialComment'
        | '/setup/SocialGlowz/components/feed/SocialPost'
        | '/setup/SocialGlowz/components/icons/NextdoorIcon'
        | '/setup/SocialGlowz/components/icons/QuoraIcon'
        | '/setup/SocialGlowz/components/icons/SnapchatIcon'
        | '/setup/SocialGlowz/components/icons/ThreadsIcon'
        | '/setup/SocialGlowz/components/kanban/KanbanBoard'
        | '/setup/SocialGlowz/components/kanban/KanbanSidebar'
        | '/setup/SocialGlowz/components/networks/DiscordView'
        | '/setup/SocialGlowz/components/networks/FacebookView'
        | '/setup/SocialGlowz/components/networks/GmailView'
        | '/setup/SocialGlowz/components/networks/InstagramView'
        | '/setup/SocialGlowz/components/networks/LinkedInView'
        | '/setup/SocialGlowz/components/networks/RedditView'
        | '/setup/SocialGlowz/components/networks/SnapchatView'
        | '/setup/SocialGlowz/components/networks/ThreadsView'
        | '/setup/SocialGlowz/components/networks/TikTokView'
        | '/setup/SocialGlowz/components/networks/TwitterView'
        | '/setup/SocialGlowz/views/LoginView'
        | '/setup/SocialGlowz/views/SessionLockView'
      views:
        | 'default'
    }
    'src/ui/setup/pages/SocialGlowz/App.vue': {
      routes:
        | '/setup/SocialGlowz/App'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/AppHeader.vue': {
      routes:
        | '/setup/SocialGlowz/components/AppHeader'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/AppRightSidebar.vue': {
      routes:
        | '/setup/SocialGlowz/components/AppRightSidebar'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/AppSettings.vue': {
      routes:
        | '/setup/SocialGlowz/components/AppSettings'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/AppSidebar.vue': {
      routes:
        | '/setup/SocialGlowz/components/AppSidebar'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/BackupRestore.vue': {
      routes:
        | '/setup/SocialGlowz/components/BackupRestore'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/BillingAccessPanel.vue': {
      routes:
        | '/setup/SocialGlowz/components/BillingAccessPanel'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/common/NetworkLogo.vue': {
      routes:
        | '/setup/SocialGlowz/components/common/NetworkLogo'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/common/SocialNetworkLogo.vue': {
      routes:
        | '/setup/SocialGlowz/components/common/SocialNetworkLogo'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/CrmToolbar.vue': {
      routes:
        | '/setup/SocialGlowz/components/CrmToolbar'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/DashboardFilters.vue': {
      routes:
        | '/setup/SocialGlowz/components/DashboardFilters'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/ExtensionParitySurface.vue': {
      routes:
        | '/setup/SocialGlowz/components/ExtensionParitySurface'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/feed/CreatePost.vue': {
      routes:
        | '/setup/SocialGlowz/components/feed/CreatePost'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/feed/SocialAvatar.vue': {
      routes:
        | '/setup/SocialGlowz/components/feed/SocialAvatar'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/feed/SocialComment.vue': {
      routes:
        | '/setup/SocialGlowz/components/feed/SocialComment'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/feed/SocialPost.vue': {
      routes:
        | '/setup/SocialGlowz/components/feed/SocialPost'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/FriendsPanel.vue': {
      routes:
        | '/setup/SocialGlowz/components/FriendsPanel'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/icons/NextdoorIcon.vue': {
      routes:
        | '/setup/SocialGlowz/components/icons/NextdoorIcon'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/icons/QuoraIcon.vue': {
      routes:
        | '/setup/SocialGlowz/components/icons/QuoraIcon'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/icons/SnapchatIcon.vue': {
      routes:
        | '/setup/SocialGlowz/components/icons/SnapchatIcon'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/icons/ThreadsIcon.vue': {
      routes:
        | '/setup/SocialGlowz/components/icons/ThreadsIcon'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/kanban/KanbanBoard.vue': {
      routes:
        | '/setup/SocialGlowz/components/kanban/KanbanBoard'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/kanban/KanbanSidebar.vue': {
      routes:
        | '/setup/SocialGlowz/components/kanban/KanbanSidebar'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/MobileLayout.vue': {
      routes:
        | '/setup/SocialGlowz/components/MobileLayout'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/MobileProfileSheet.vue': {
      routes:
        | '/setup/SocialGlowz/components/MobileProfileSheet'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/MobileSettingsSheet.vue': {
      routes:
        | '/setup/SocialGlowz/components/MobileSettingsSheet'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/NetworkBrandIcon.vue': {
      routes:
        | '/setup/SocialGlowz/components/NetworkBrandIcon'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/DiscordView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/DiscordView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/FacebookView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/FacebookView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/GmailView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/GmailView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/InstagramView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/InstagramView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/LinkedInView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/LinkedInView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/RedditView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/RedditView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/SnapchatView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/SnapchatView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/ThreadsView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/ThreadsView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/TikTokView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/TikTokView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/networks/TwitterView.vue': {
      routes:
        | '/setup/SocialGlowz/components/networks/TwitterView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/NetworkWebviewHost.vue': {
      routes:
        | '/setup/SocialGlowz/components/NetworkWebviewHost'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/OnboardingFlow.vue': {
      routes:
        | '/setup/SocialGlowz/components/OnboardingFlow'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/PostAuthSyncOverlay.vue': {
      routes:
        | '/setup/SocialGlowz/components/PostAuthSyncOverlay'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/ProfileSwitcher.vue': {
      routes:
        | '/setup/SocialGlowz/components/ProfileSwitcher'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/SignupNudge.vue': {
      routes:
        | '/setup/SocialGlowz/components/SignupNudge'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/SocialLogin.vue': {
      routes:
        | '/setup/SocialGlowz/components/SocialLogin'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/components/Unauthorized.vue': {
      routes:
        | '/setup/SocialGlowz/components/Unauthorized'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/views/LoginView.vue': {
      routes:
        | '/setup/SocialGlowz/views/LoginView'
      views:
        | never
    }
    'src/ui/setup/pages/SocialGlowz/views/SessionLockView.vue': {
      routes:
        | '/setup/SocialGlowz/views/SessionLockView'
      views:
        | never
    }
    'src/ui/setup/pages/update.vue': {
      routes:
        | '/setup/update'
      views:
        | never
    }
    'src/ui/side-panel/pages/index.vue': {
      routes:
        | '/side-panel/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
