/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<
      '/action-popup/',
      '/action-popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/playground': RouteRecordInfo<
      '/action-popup/playground',
      '/action-popup/playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/404': RouteRecordInfo<
      '/common/404',
      '/common/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/about': RouteRecordInfo<
      '/common/about',
      '/common/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/change-log': RouteRecordInfo<
      '/common/change-log',
      '/common/change-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/features': RouteRecordInfo<
      '/common/features',
      '/common/features',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/help': RouteRecordInfo<
      '/common/help',
      '/common/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/privacy-policy': RouteRecordInfo<
      '/common/privacy-policy',
      '/common/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/common/terms-of-service': RouteRecordInfo<
      '/common/terms-of-service',
      '/common/terms-of-service',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content-script-iframe/': RouteRecordInfo<
      '/content-script-iframe/',
      '/content-script-iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools-panel/': RouteRecordInfo<
      '/devtools-panel/',
      '/devtools-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/': RouteRecordInfo<
      '/options-page/',
      '/options-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows': RouteRecordInfo<
      '/setup/CommunityGlows',
      '/setup/CommunityGlows',
      Record<never, never>,
      Record<never, never>,
      | '/setup/CommunityGlows/App'
      | '/setup/CommunityGlows/components/AppHeader'
      | '/setup/CommunityGlows/components/AppRightSidebar'
      | '/setup/CommunityGlows/components/AppSettings'
      | '/setup/CommunityGlows/components/AppSidebar'
      | '/setup/CommunityGlows/components/BackupRestore'
      | '/setup/CommunityGlows/components/BillingAccessPanel'
      | '/setup/CommunityGlows/components/CrmSidebarWidget'
      | '/setup/CommunityGlows/components/CrmToolbar'
      | '/setup/CommunityGlows/components/DashboardFilters'
      | '/setup/CommunityGlows/components/DesktopControlBar'
      | '/setup/CommunityGlows/components/DesktopQuickNavigation'
      | '/setup/CommunityGlows/components/ExtensionParitySurface'
      | '/setup/CommunityGlows/components/FriendsPanel'
      | '/setup/CommunityGlows/components/KeyboardShortcuts'
      | '/setup/CommunityGlows/components/MobileLayout'
      | '/setup/CommunityGlows/components/MobileProfileSheet'
      | '/setup/CommunityGlows/components/MobileSettingsSheet'
      | '/setup/CommunityGlows/components/NetworkBrandIcon'
      | '/setup/CommunityGlows/components/NetworkWebviewHost'
      | '/setup/CommunityGlows/components/OnboardingFlow'
      | '/setup/CommunityGlows/components/PostAuthSyncOverlay'
      | '/setup/CommunityGlows/components/ProductAccessGate'
      | '/setup/CommunityGlows/components/ProfileAvatarDialog'
      | '/setup/CommunityGlows/components/ProfileAvatarEditor'
      | '/setup/CommunityGlows/components/ProfileManagerDialog'
      | '/setup/CommunityGlows/components/ProfileSwitcher'
      | '/setup/CommunityGlows/components/SignupNudge'
      | '/setup/CommunityGlows/components/SocialLogin'
      | '/setup/CommunityGlows/components/Unauthorized'
      | '/setup/CommunityGlows/components/common/NetworkLogo'
      | '/setup/CommunityGlows/components/common/SocialNetworkLogo'
      | '/setup/CommunityGlows/components/feed/CreatePost'
      | '/setup/CommunityGlows/components/feed/SocialAvatar'
      | '/setup/CommunityGlows/components/feed/SocialComment'
      | '/setup/CommunityGlows/components/feed/SocialPost'
      | '/setup/CommunityGlows/components/icons/NextdoorIcon'
      | '/setup/CommunityGlows/components/icons/QuoraIcon'
      | '/setup/CommunityGlows/components/icons/SnapchatIcon'
      | '/setup/CommunityGlows/components/icons/ThreadsIcon'
      | '/setup/CommunityGlows/components/kanban/KanbanBoard'
      | '/setup/CommunityGlows/components/kanban/KanbanSidebar'
      | '/setup/CommunityGlows/components/networks/DiscordView'
      | '/setup/CommunityGlows/components/networks/FacebookView'
      | '/setup/CommunityGlows/components/networks/GmailView'
      | '/setup/CommunityGlows/components/networks/InstagramView'
      | '/setup/CommunityGlows/components/networks/LinkedInView'
      | '/setup/CommunityGlows/components/networks/NetworkTwoColumnLayout'
      | '/setup/CommunityGlows/components/networks/RedditView'
      | '/setup/CommunityGlows/components/networks/SnapchatView'
      | '/setup/CommunityGlows/components/networks/ThreadsView'
      | '/setup/CommunityGlows/components/networks/TikTokView'
      | '/setup/CommunityGlows/components/networks/TwitterView'
      | '/setup/CommunityGlows/components/tasks/ExtensionTaskCapture'
      | '/setup/CommunityGlows/components/tasks/TaskBoard'
      | '/setup/CommunityGlows/components/tasks/TaskForm'
      | '/setup/CommunityGlows/components/ui/SectionEyebrow'
      | '/setup/CommunityGlows/components/ui/SgAvatar'
      | '/setup/CommunityGlows/components/ui/SgBadge'
      | '/setup/CommunityGlows/components/ui/SgButton'
      | '/setup/CommunityGlows/components/ui/SgDialog'
      | '/setup/CommunityGlows/components/ui/SgIcon'
      | '/setup/CommunityGlows/components/ui/SgInput'
      | '/setup/CommunityGlows/components/ui/SgMultiSelect'
      | '/setup/CommunityGlows/components/ui/SgPassword'
      | '/setup/CommunityGlows/components/ui/SgSelect'
      | '/setup/CommunityGlows/components/ui/SgSheet'
      | '/setup/CommunityGlows/components/ui/SgSpinner'
      | '/setup/CommunityGlows/components/ui/SgStatusPill'
      | '/setup/CommunityGlows/components/ui/SgSwitch'
      | '/setup/CommunityGlows/components/ui/SgTextarea'
      | '/setup/CommunityGlows/views/LoginView'
      | '/setup/CommunityGlows/views/SessionLockView'
      | '/setup/CommunityGlows/views/TasksView'
    >,
    '/setup/CommunityGlows/App': RouteRecordInfo<
      '/setup/CommunityGlows/App',
      '/setup/CommunityGlows/App',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/AppHeader': RouteRecordInfo<
      '/setup/CommunityGlows/components/AppHeader',
      '/setup/CommunityGlows/components/AppHeader',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/AppRightSidebar': RouteRecordInfo<
      '/setup/CommunityGlows/components/AppRightSidebar',
      '/setup/CommunityGlows/components/AppRightSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/AppSettings': RouteRecordInfo<
      '/setup/CommunityGlows/components/AppSettings',
      '/setup/CommunityGlows/components/AppSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/AppSidebar': RouteRecordInfo<
      '/setup/CommunityGlows/components/AppSidebar',
      '/setup/CommunityGlows/components/AppSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/BackupRestore': RouteRecordInfo<
      '/setup/CommunityGlows/components/BackupRestore',
      '/setup/CommunityGlows/components/BackupRestore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/BillingAccessPanel': RouteRecordInfo<
      '/setup/CommunityGlows/components/BillingAccessPanel',
      '/setup/CommunityGlows/components/BillingAccessPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/common/NetworkLogo': RouteRecordInfo<
      '/setup/CommunityGlows/components/common/NetworkLogo',
      '/setup/CommunityGlows/components/common/NetworkLogo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/common/SocialNetworkLogo': RouteRecordInfo<
      '/setup/CommunityGlows/components/common/SocialNetworkLogo',
      '/setup/CommunityGlows/components/common/SocialNetworkLogo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/CrmSidebarWidget': RouteRecordInfo<
      '/setup/CommunityGlows/components/CrmSidebarWidget',
      '/setup/CommunityGlows/components/CrmSidebarWidget',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/CrmToolbar': RouteRecordInfo<
      '/setup/CommunityGlows/components/CrmToolbar',
      '/setup/CommunityGlows/components/CrmToolbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/DashboardFilters': RouteRecordInfo<
      '/setup/CommunityGlows/components/DashboardFilters',
      '/setup/CommunityGlows/components/DashboardFilters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/DesktopControlBar': RouteRecordInfo<
      '/setup/CommunityGlows/components/DesktopControlBar',
      '/setup/CommunityGlows/components/DesktopControlBar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/DesktopQuickNavigation': RouteRecordInfo<
      '/setup/CommunityGlows/components/DesktopQuickNavigation',
      '/setup/CommunityGlows/components/DesktopQuickNavigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ExtensionParitySurface': RouteRecordInfo<
      '/setup/CommunityGlows/components/ExtensionParitySurface',
      '/setup/CommunityGlows/components/ExtensionParitySurface',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/feed/CreatePost': RouteRecordInfo<
      '/setup/CommunityGlows/components/feed/CreatePost',
      '/setup/CommunityGlows/components/feed/CreatePost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/feed/SocialAvatar': RouteRecordInfo<
      '/setup/CommunityGlows/components/feed/SocialAvatar',
      '/setup/CommunityGlows/components/feed/SocialAvatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/feed/SocialComment': RouteRecordInfo<
      '/setup/CommunityGlows/components/feed/SocialComment',
      '/setup/CommunityGlows/components/feed/SocialComment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/feed/SocialPost': RouteRecordInfo<
      '/setup/CommunityGlows/components/feed/SocialPost',
      '/setup/CommunityGlows/components/feed/SocialPost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/FriendsPanel': RouteRecordInfo<
      '/setup/CommunityGlows/components/FriendsPanel',
      '/setup/CommunityGlows/components/FriendsPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/icons/NextdoorIcon': RouteRecordInfo<
      '/setup/CommunityGlows/components/icons/NextdoorIcon',
      '/setup/CommunityGlows/components/icons/NextdoorIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/icons/QuoraIcon': RouteRecordInfo<
      '/setup/CommunityGlows/components/icons/QuoraIcon',
      '/setup/CommunityGlows/components/icons/QuoraIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/icons/SnapchatIcon': RouteRecordInfo<
      '/setup/CommunityGlows/components/icons/SnapchatIcon',
      '/setup/CommunityGlows/components/icons/SnapchatIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/icons/ThreadsIcon': RouteRecordInfo<
      '/setup/CommunityGlows/components/icons/ThreadsIcon',
      '/setup/CommunityGlows/components/icons/ThreadsIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/kanban/KanbanBoard': RouteRecordInfo<
      '/setup/CommunityGlows/components/kanban/KanbanBoard',
      '/setup/CommunityGlows/components/kanban/KanbanBoard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/kanban/KanbanSidebar': RouteRecordInfo<
      '/setup/CommunityGlows/components/kanban/KanbanSidebar',
      '/setup/CommunityGlows/components/kanban/KanbanSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/KeyboardShortcuts': RouteRecordInfo<
      '/setup/CommunityGlows/components/KeyboardShortcuts',
      '/setup/CommunityGlows/components/KeyboardShortcuts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/MobileLayout': RouteRecordInfo<
      '/setup/CommunityGlows/components/MobileLayout',
      '/setup/CommunityGlows/components/MobileLayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/MobileProfileSheet': RouteRecordInfo<
      '/setup/CommunityGlows/components/MobileProfileSheet',
      '/setup/CommunityGlows/components/MobileProfileSheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/MobileSettingsSheet': RouteRecordInfo<
      '/setup/CommunityGlows/components/MobileSettingsSheet',
      '/setup/CommunityGlows/components/MobileSettingsSheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/NetworkBrandIcon': RouteRecordInfo<
      '/setup/CommunityGlows/components/NetworkBrandIcon',
      '/setup/CommunityGlows/components/NetworkBrandIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/DiscordView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/DiscordView',
      '/setup/CommunityGlows/components/networks/DiscordView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/FacebookView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/FacebookView',
      '/setup/CommunityGlows/components/networks/FacebookView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/GmailView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/GmailView',
      '/setup/CommunityGlows/components/networks/GmailView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/InstagramView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/InstagramView',
      '/setup/CommunityGlows/components/networks/InstagramView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/LinkedInView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/LinkedInView',
      '/setup/CommunityGlows/components/networks/LinkedInView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/NetworkTwoColumnLayout': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/NetworkTwoColumnLayout',
      '/setup/CommunityGlows/components/networks/NetworkTwoColumnLayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/RedditView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/RedditView',
      '/setup/CommunityGlows/components/networks/RedditView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/SnapchatView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/SnapchatView',
      '/setup/CommunityGlows/components/networks/SnapchatView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/ThreadsView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/ThreadsView',
      '/setup/CommunityGlows/components/networks/ThreadsView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/TikTokView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/TikTokView',
      '/setup/CommunityGlows/components/networks/TikTokView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/networks/TwitterView': RouteRecordInfo<
      '/setup/CommunityGlows/components/networks/TwitterView',
      '/setup/CommunityGlows/components/networks/TwitterView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/NetworkWebviewHost': RouteRecordInfo<
      '/setup/CommunityGlows/components/NetworkWebviewHost',
      '/setup/CommunityGlows/components/NetworkWebviewHost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/OnboardingFlow': RouteRecordInfo<
      '/setup/CommunityGlows/components/OnboardingFlow',
      '/setup/CommunityGlows/components/OnboardingFlow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/PostAuthSyncOverlay': RouteRecordInfo<
      '/setup/CommunityGlows/components/PostAuthSyncOverlay',
      '/setup/CommunityGlows/components/PostAuthSyncOverlay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ProductAccessGate': RouteRecordInfo<
      '/setup/CommunityGlows/components/ProductAccessGate',
      '/setup/CommunityGlows/components/ProductAccessGate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ProfileAvatarDialog': RouteRecordInfo<
      '/setup/CommunityGlows/components/ProfileAvatarDialog',
      '/setup/CommunityGlows/components/ProfileAvatarDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ProfileAvatarEditor': RouteRecordInfo<
      '/setup/CommunityGlows/components/ProfileAvatarEditor',
      '/setup/CommunityGlows/components/ProfileAvatarEditor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ProfileManagerDialog': RouteRecordInfo<
      '/setup/CommunityGlows/components/ProfileManagerDialog',
      '/setup/CommunityGlows/components/ProfileManagerDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ProfileSwitcher': RouteRecordInfo<
      '/setup/CommunityGlows/components/ProfileSwitcher',
      '/setup/CommunityGlows/components/ProfileSwitcher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/SignupNudge': RouteRecordInfo<
      '/setup/CommunityGlows/components/SignupNudge',
      '/setup/CommunityGlows/components/SignupNudge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/SocialLogin': RouteRecordInfo<
      '/setup/CommunityGlows/components/SocialLogin',
      '/setup/CommunityGlows/components/SocialLogin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/tasks/ExtensionTaskCapture': RouteRecordInfo<
      '/setup/CommunityGlows/components/tasks/ExtensionTaskCapture',
      '/setup/CommunityGlows/components/tasks/ExtensionTaskCapture',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/tasks/TaskBoard': RouteRecordInfo<
      '/setup/CommunityGlows/components/tasks/TaskBoard',
      '/setup/CommunityGlows/components/tasks/TaskBoard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/tasks/TaskForm': RouteRecordInfo<
      '/setup/CommunityGlows/components/tasks/TaskForm',
      '/setup/CommunityGlows/components/tasks/TaskForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SectionEyebrow': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SectionEyebrow',
      '/setup/CommunityGlows/components/ui/SectionEyebrow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgAvatar': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgAvatar',
      '/setup/CommunityGlows/components/ui/SgAvatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgBadge': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgBadge',
      '/setup/CommunityGlows/components/ui/SgBadge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgButton': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgButton',
      '/setup/CommunityGlows/components/ui/SgButton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgDialog': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgDialog',
      '/setup/CommunityGlows/components/ui/SgDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgIcon': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgIcon',
      '/setup/CommunityGlows/components/ui/SgIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgInput': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgInput',
      '/setup/CommunityGlows/components/ui/SgInput',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgMultiSelect': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgMultiSelect',
      '/setup/CommunityGlows/components/ui/SgMultiSelect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgPassword': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgPassword',
      '/setup/CommunityGlows/components/ui/SgPassword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgSelect': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgSelect',
      '/setup/CommunityGlows/components/ui/SgSelect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgSheet': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgSheet',
      '/setup/CommunityGlows/components/ui/SgSheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgSpinner': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgSpinner',
      '/setup/CommunityGlows/components/ui/SgSpinner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgStatusPill': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgStatusPill',
      '/setup/CommunityGlows/components/ui/SgStatusPill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgSwitch': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgSwitch',
      '/setup/CommunityGlows/components/ui/SgSwitch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/ui/SgTextarea': RouteRecordInfo<
      '/setup/CommunityGlows/components/ui/SgTextarea',
      '/setup/CommunityGlows/components/ui/SgTextarea',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/components/Unauthorized': RouteRecordInfo<
      '/setup/CommunityGlows/components/Unauthorized',
      '/setup/CommunityGlows/components/Unauthorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/views/LoginView': RouteRecordInfo<
      '/setup/CommunityGlows/views/LoginView',
      '/setup/CommunityGlows/views/LoginView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/views/SessionLockView': RouteRecordInfo<
      '/setup/CommunityGlows/views/SessionLockView',
      '/setup/CommunityGlows/views/SessionLockView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/CommunityGlows/views/TasksView': RouteRecordInfo<
      '/setup/CommunityGlows/views/TasksView',
      '/setup/CommunityGlows/views/TasksView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/install': RouteRecordInfo<
      '/setup/install',
      '/setup/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup/update': RouteRecordInfo<
      '/setup/update',
      '/setup/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/side-panel/': RouteRecordInfo<
      '/side-panel/',
      '/side-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/ui/action-popup/pages/index.vue': {
      routes:
        | '/action-popup/'
      views:
        | never
    }
    'src/ui/action-popup/pages/playground.vue': {
      routes:
        | '/action-popup/playground'
      views:
        | never
    }
    'src/ui/common/pages/404.vue': {
      routes:
        | '/common/404'
      views:
        | never
    }
    'src/ui/common/pages/about.vue': {
      routes:
        | '/common/about'
      views:
        | never
    }
    'src/ui/common/pages/change-log.vue': {
      routes:
        | '/common/change-log'
      views:
        | never
    }
    'src/ui/common/pages/features.vue': {
      routes:
        | '/common/features'
      views:
        | never
    }
    'src/ui/common/pages/help.vue': {
      routes:
        | '/common/help'
      views:
        | never
    }
    'src/ui/common/pages/privacy-policy.vue': {
      routes:
        | '/common/privacy-policy'
      views:
        | never
    }
    'src/ui/common/pages/terms-of-service.vue': {
      routes:
        | '/common/terms-of-service'
      views:
        | never
    }
    'src/ui/content-script-iframe/pages/index.vue': {
      routes:
        | '/content-script-iframe/'
      views:
        | never
    }
    'src/ui/devtools-panel/pages/index.vue': {
      routes:
        | '/devtools-panel/'
      views:
        | never
    }
    'src/ui/options-page/pages/index.vue': {
      routes:
        | '/options-page/'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows.vue': {
      routes:
        | '/setup/CommunityGlows'
        | '/setup/CommunityGlows/App'
        | '/setup/CommunityGlows/components/AppHeader'
        | '/setup/CommunityGlows/components/AppRightSidebar'
        | '/setup/CommunityGlows/components/AppSettings'
        | '/setup/CommunityGlows/components/AppSidebar'
        | '/setup/CommunityGlows/components/BackupRestore'
        | '/setup/CommunityGlows/components/BillingAccessPanel'
        | '/setup/CommunityGlows/components/CrmSidebarWidget'
        | '/setup/CommunityGlows/components/CrmToolbar'
        | '/setup/CommunityGlows/components/DashboardFilters'
        | '/setup/CommunityGlows/components/DesktopControlBar'
        | '/setup/CommunityGlows/components/DesktopQuickNavigation'
        | '/setup/CommunityGlows/components/ExtensionParitySurface'
        | '/setup/CommunityGlows/components/FriendsPanel'
        | '/setup/CommunityGlows/components/KeyboardShortcuts'
        | '/setup/CommunityGlows/components/MobileLayout'
        | '/setup/CommunityGlows/components/MobileProfileSheet'
        | '/setup/CommunityGlows/components/MobileSettingsSheet'
        | '/setup/CommunityGlows/components/NetworkBrandIcon'
        | '/setup/CommunityGlows/components/NetworkWebviewHost'
        | '/setup/CommunityGlows/components/OnboardingFlow'
        | '/setup/CommunityGlows/components/PostAuthSyncOverlay'
        | '/setup/CommunityGlows/components/ProductAccessGate'
        | '/setup/CommunityGlows/components/ProfileAvatarDialog'
        | '/setup/CommunityGlows/components/ProfileAvatarEditor'
        | '/setup/CommunityGlows/components/ProfileManagerDialog'
        | '/setup/CommunityGlows/components/ProfileSwitcher'
        | '/setup/CommunityGlows/components/SignupNudge'
        | '/setup/CommunityGlows/components/SocialLogin'
        | '/setup/CommunityGlows/components/Unauthorized'
        | '/setup/CommunityGlows/components/common/NetworkLogo'
        | '/setup/CommunityGlows/components/common/SocialNetworkLogo'
        | '/setup/CommunityGlows/components/feed/CreatePost'
        | '/setup/CommunityGlows/components/feed/SocialAvatar'
        | '/setup/CommunityGlows/components/feed/SocialComment'
        | '/setup/CommunityGlows/components/feed/SocialPost'
        | '/setup/CommunityGlows/components/icons/NextdoorIcon'
        | '/setup/CommunityGlows/components/icons/QuoraIcon'
        | '/setup/CommunityGlows/components/icons/SnapchatIcon'
        | '/setup/CommunityGlows/components/icons/ThreadsIcon'
        | '/setup/CommunityGlows/components/kanban/KanbanBoard'
        | '/setup/CommunityGlows/components/kanban/KanbanSidebar'
        | '/setup/CommunityGlows/components/networks/DiscordView'
        | '/setup/CommunityGlows/components/networks/FacebookView'
        | '/setup/CommunityGlows/components/networks/GmailView'
        | '/setup/CommunityGlows/components/networks/InstagramView'
        | '/setup/CommunityGlows/components/networks/LinkedInView'
        | '/setup/CommunityGlows/components/networks/NetworkTwoColumnLayout'
        | '/setup/CommunityGlows/components/networks/RedditView'
        | '/setup/CommunityGlows/components/networks/SnapchatView'
        | '/setup/CommunityGlows/components/networks/ThreadsView'
        | '/setup/CommunityGlows/components/networks/TikTokView'
        | '/setup/CommunityGlows/components/networks/TwitterView'
        | '/setup/CommunityGlows/components/tasks/ExtensionTaskCapture'
        | '/setup/CommunityGlows/components/tasks/TaskBoard'
        | '/setup/CommunityGlows/components/tasks/TaskForm'
        | '/setup/CommunityGlows/components/ui/SectionEyebrow'
        | '/setup/CommunityGlows/components/ui/SgAvatar'
        | '/setup/CommunityGlows/components/ui/SgBadge'
        | '/setup/CommunityGlows/components/ui/SgButton'
        | '/setup/CommunityGlows/components/ui/SgDialog'
        | '/setup/CommunityGlows/components/ui/SgIcon'
        | '/setup/CommunityGlows/components/ui/SgInput'
        | '/setup/CommunityGlows/components/ui/SgMultiSelect'
        | '/setup/CommunityGlows/components/ui/SgPassword'
        | '/setup/CommunityGlows/components/ui/SgSelect'
        | '/setup/CommunityGlows/components/ui/SgSheet'
        | '/setup/CommunityGlows/components/ui/SgSpinner'
        | '/setup/CommunityGlows/components/ui/SgStatusPill'
        | '/setup/CommunityGlows/components/ui/SgSwitch'
        | '/setup/CommunityGlows/components/ui/SgTextarea'
        | '/setup/CommunityGlows/views/LoginView'
        | '/setup/CommunityGlows/views/SessionLockView'
        | '/setup/CommunityGlows/views/TasksView'
      views:
        | 'default'
    }
    'src/ui/setup/pages/CommunityGlows/App.vue': {
      routes:
        | '/setup/CommunityGlows/App'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/AppHeader.vue': {
      routes:
        | '/setup/CommunityGlows/components/AppHeader'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/AppRightSidebar.vue': {
      routes:
        | '/setup/CommunityGlows/components/AppRightSidebar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/AppSettings.vue': {
      routes:
        | '/setup/CommunityGlows/components/AppSettings'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/AppSidebar.vue': {
      routes:
        | '/setup/CommunityGlows/components/AppSidebar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/BackupRestore.vue': {
      routes:
        | '/setup/CommunityGlows/components/BackupRestore'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/BillingAccessPanel.vue': {
      routes:
        | '/setup/CommunityGlows/components/BillingAccessPanel'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/common/NetworkLogo.vue': {
      routes:
        | '/setup/CommunityGlows/components/common/NetworkLogo'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/common/SocialNetworkLogo.vue': {
      routes:
        | '/setup/CommunityGlows/components/common/SocialNetworkLogo'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/CrmSidebarWidget.vue': {
      routes:
        | '/setup/CommunityGlows/components/CrmSidebarWidget'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/CrmToolbar.vue': {
      routes:
        | '/setup/CommunityGlows/components/CrmToolbar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/DashboardFilters.vue': {
      routes:
        | '/setup/CommunityGlows/components/DashboardFilters'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/DesktopControlBar.vue': {
      routes:
        | '/setup/CommunityGlows/components/DesktopControlBar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/DesktopQuickNavigation.vue': {
      routes:
        | '/setup/CommunityGlows/components/DesktopQuickNavigation'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ExtensionParitySurface.vue': {
      routes:
        | '/setup/CommunityGlows/components/ExtensionParitySurface'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/feed/CreatePost.vue': {
      routes:
        | '/setup/CommunityGlows/components/feed/CreatePost'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/feed/SocialAvatar.vue': {
      routes:
        | '/setup/CommunityGlows/components/feed/SocialAvatar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/feed/SocialComment.vue': {
      routes:
        | '/setup/CommunityGlows/components/feed/SocialComment'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/feed/SocialPost.vue': {
      routes:
        | '/setup/CommunityGlows/components/feed/SocialPost'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/FriendsPanel.vue': {
      routes:
        | '/setup/CommunityGlows/components/FriendsPanel'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/icons/NextdoorIcon.vue': {
      routes:
        | '/setup/CommunityGlows/components/icons/NextdoorIcon'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/icons/QuoraIcon.vue': {
      routes:
        | '/setup/CommunityGlows/components/icons/QuoraIcon'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/icons/SnapchatIcon.vue': {
      routes:
        | '/setup/CommunityGlows/components/icons/SnapchatIcon'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/icons/ThreadsIcon.vue': {
      routes:
        | '/setup/CommunityGlows/components/icons/ThreadsIcon'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/kanban/KanbanBoard.vue': {
      routes:
        | '/setup/CommunityGlows/components/kanban/KanbanBoard'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/kanban/KanbanSidebar.vue': {
      routes:
        | '/setup/CommunityGlows/components/kanban/KanbanSidebar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/KeyboardShortcuts.vue': {
      routes:
        | '/setup/CommunityGlows/components/KeyboardShortcuts'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/MobileLayout.vue': {
      routes:
        | '/setup/CommunityGlows/components/MobileLayout'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/MobileProfileSheet.vue': {
      routes:
        | '/setup/CommunityGlows/components/MobileProfileSheet'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/MobileSettingsSheet.vue': {
      routes:
        | '/setup/CommunityGlows/components/MobileSettingsSheet'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/NetworkBrandIcon.vue': {
      routes:
        | '/setup/CommunityGlows/components/NetworkBrandIcon'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/DiscordView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/DiscordView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/FacebookView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/FacebookView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/GmailView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/GmailView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/InstagramView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/InstagramView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/LinkedInView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/LinkedInView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/NetworkTwoColumnLayout.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/NetworkTwoColumnLayout'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/RedditView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/RedditView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/SnapchatView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/SnapchatView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/ThreadsView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/ThreadsView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/TikTokView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/TikTokView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/networks/TwitterView.vue': {
      routes:
        | '/setup/CommunityGlows/components/networks/TwitterView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/NetworkWebviewHost.vue': {
      routes:
        | '/setup/CommunityGlows/components/NetworkWebviewHost'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/OnboardingFlow.vue': {
      routes:
        | '/setup/CommunityGlows/components/OnboardingFlow'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/PostAuthSyncOverlay.vue': {
      routes:
        | '/setup/CommunityGlows/components/PostAuthSyncOverlay'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ProductAccessGate.vue': {
      routes:
        | '/setup/CommunityGlows/components/ProductAccessGate'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ProfileAvatarDialog.vue': {
      routes:
        | '/setup/CommunityGlows/components/ProfileAvatarDialog'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ProfileAvatarEditor.vue': {
      routes:
        | '/setup/CommunityGlows/components/ProfileAvatarEditor'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ProfileManagerDialog.vue': {
      routes:
        | '/setup/CommunityGlows/components/ProfileManagerDialog'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ProfileSwitcher.vue': {
      routes:
        | '/setup/CommunityGlows/components/ProfileSwitcher'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/SignupNudge.vue': {
      routes:
        | '/setup/CommunityGlows/components/SignupNudge'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/SocialLogin.vue': {
      routes:
        | '/setup/CommunityGlows/components/SocialLogin'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/tasks/ExtensionTaskCapture.vue': {
      routes:
        | '/setup/CommunityGlows/components/tasks/ExtensionTaskCapture'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/tasks/TaskBoard.vue': {
      routes:
        | '/setup/CommunityGlows/components/tasks/TaskBoard'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/tasks/TaskForm.vue': {
      routes:
        | '/setup/CommunityGlows/components/tasks/TaskForm'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SectionEyebrow.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SectionEyebrow'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgAvatar.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgAvatar'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgBadge.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgBadge'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgButton.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgButton'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgDialog.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgDialog'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgIcon.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgIcon'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgInput.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgInput'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgMultiSelect.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgMultiSelect'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgPassword.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgPassword'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgSelect.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgSelect'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgSheet.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgSheet'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgSpinner.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgSpinner'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgStatusPill.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgStatusPill'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgSwitch.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgSwitch'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/ui/SgTextarea.vue': {
      routes:
        | '/setup/CommunityGlows/components/ui/SgTextarea'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/components/Unauthorized.vue': {
      routes:
        | '/setup/CommunityGlows/components/Unauthorized'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/views/LoginView.vue': {
      routes:
        | '/setup/CommunityGlows/views/LoginView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/views/SessionLockView.vue': {
      routes:
        | '/setup/CommunityGlows/views/SessionLockView'
      views:
        | never
    }
    'src/ui/setup/pages/CommunityGlows/views/TasksView.vue': {
      routes:
        | '/setup/CommunityGlows/views/TasksView'
      views:
        | never
    }
    'src/ui/setup/pages/install.vue': {
      routes:
        | '/setup/install'
      views:
        | never
    }
    'src/ui/setup/pages/update.vue': {
      routes:
        | '/setup/update'
      views:
        | never
    }
    'src/ui/side-panel/pages/index.vue': {
      routes:
        | '/side-panel/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
